name: nullinside-api-twitch-bot
services:
    nullinside-api-twitch-bot:
        logging:
            driver: loki
            options:
                'loki-url': 'http://192.168.1.4:3100/loki/api/v1/push'
        container_name: nullinside-api-twitch-bot
        environment:
            - TWITCH_BOT_CLIENT_ID
            - TWITCH_BOT_CLIENT_SECRET
            - TWITCH_BOT_CLIENT_REDIRECT
            - MYSQL_SERVER
            - MYSQL_USERNAME
            - MYSQL_PASSWORD
        ports:
            - 8086:8080
            - 8085:8081
        restart: unless-stopped
        image: nullinside-api-twitch-bot:latest
