using Moq;

using Nullinside.Api.Common.Twitch;
using Nullinside.Api.TwitchBot.ChatRules;
using Nullinside.Api.TwitchBot.Model;

namespace Nullinside.Api.TwitchBot.Tests.ChatRules;

/// <summary>
///   Tests the <see cref="BestCheapViewers" /> class.
/// </summary>
public class BestCheapViewersTests : AChatRuleUnitTestBase<BestCheapViewers> {
  /// <summary>
  ///   Tests strings that have been typed in chats.
  /// </summary>
  /// <param name="badString">The string that should fail.</param>
  [Test]
  [TestCase("@4fRLxwrcZ Wanna more viewers? Best followers and viewers on streamboo .live")]
  [TestCase("@anarchy_gaming03 Streaming into the void? boosting channels from ghost town to war zone with nezhna .com")]
  [TestCase("@arcadiawildbill Best viewers  ***")]
  [TestCase("@boggett_ Best viewers  streamboo .com (remove the space)")]
  [TestCase("@checkingmylootz Top Viewers ***")]
  [TestCase("@chronocidex We specialize in promoting Twitch channels — check out our website: nezhna .com")]
  [TestCase("@CkYKHL Want popularity? Buy viewers streamboo. com")]
  [TestCase("@darkwolfca Best viewers  ***")]
  [TestCase("@darkwolfca Viewers ***")]
  [TestCase("@dragon_heart305 Best Viewers highspark.online")]
  [TestCase("@dragon_heart305 Top Viewers smmvu.ru")]
  [TestCase("@elakenttv We specialize in promoting Twitch channels — check out our website: nezhna .com")]
  [TestCase("@ethuins Viewers ***")]
  [TestCase("@floridean Top viewers smmtop55.ru")]
  [TestCase("@ghlitto275 B̬est viewers  on streamboo .com (remove the space)")]
  [TestCase("@golden_jaypc Viewers smmtop59.ru")]
  [TestCase("@gothmom1983 Streaming into the void? boosting channels from ghost town to war zone with nezhna .com remove spaces")]
  [TestCase("@heavyd3vy B̬est viewers  on streamboo .com (remove the space)")]
  [TestCase("@huskyshyper Best viewers  smmtop47.ru")]
  [TestCase("@jayjamss B̬est viewers  on streamboo .com (remove the space)")]
  [TestCase("@jayjamss Top Viewers streamboo .com")]
  [TestCase("@jayjamss Viewers ***")]
  [TestCase("@jayjamss Viewers streamboo. com (remove the space")]
  [TestCase("@jeezy2x Top viewers ***")]
  [TestCase("@Jg412 did уоu trу Stream Viewеrs dott org ? АI sеrviсе for get nеw rеal viewеrs")]
  [TestCase("@jigokunoinu Become popular with boostcorex.ru")]
  [TestCase("@jigokunoinu Become popular with highcorex.online")]
  [TestCase("@jigokunoinu Viewers smmbest3.ru")]
  [TestCase("@k0r_b0r Cheapest Viewers boosttask.ru")]
  [TestCase("@kingdrop24 Top Viewers hypeb.online")]
  [TestCase("@lordinsanityiii Become popular with ***")]
  [TestCase("@lordinsanityiii Best Viewers *** (free 25 viewers)")]
  [TestCase("@lunamaria369 Become popular with ***")]
  [TestCase("@mcnightmare91 Top Viewers streamboo .com")]
  [TestCase("@mightyowl252 Cheapest Viewers boosttask.ru")]
  [TestCase("@movie1011 Top Viewers smmedge.online")]
  [TestCase("@muffinstuffintv did уоu try Streаm Viewers dott org ? АI serviсе fоr get new rеаl viеwеrs")]
  [TestCase("@N9PPDg2Lp Wanna more viewers? Best followers and viewers on streamboo .live")]
  [TestCase("@nerdyzane_vt Become popular with hightask.online")]
  [TestCase("@nerdyzane_vt Best viewers  streamboo .com (remove the space)")]
  [TestCase("@night_medjumper Top Viewers streamboo .live")]
  [TestCase("@panxhitop Top Viewers smmly1.online")]
  [TestCase("@residentxgirly Viewers smmhype2.online")]
  [TestCase("@rockfaik Viewers smmtop53.online")]
  [TestCase("@ryuushefu Viewers streamboo. com (remove the space")]
  [TestCase("@sariaslp Top viewers ***")]
  [TestCase("@shadowtimgaming Cheap Viewers  smmtask.ru (free test)")]
  [TestCase("@sirenity_gaming Cheap Viewers  *** (free test)")]
  [TestCase("@sOwbKe Want popularity? Buy viewers streamboo. com")]
  [TestCase("@srsuricat0 Best viewers smmtop39.ru")]
  [TestCase("@srsuricat0 Top viewers smmtop52.ru")]
  [TestCase("@thepropagationstream Viewers smmbest7.online")]
  [TestCase("@unicornpriincess Viewers smmtop53.ru")]
  [TestCase("@vikingkray B̬est viewers  on streamboo .com (remove the space)")]
  [TestCase("@voidcollections Become popular with ***")]
  [TestCase("@voidcollections Best viewers  ***")]
  [TestCase("@voidcollections Best Viewers ***")]
  [TestCase("@voidcollections Best Viewers ***  (free 25 viewers)")]
  [TestCase("@voidcollections Top Viewers ***")]
  [TestCase("@voidcollections Top Viewers *** (25 free viewers)")]
  [TestCase("@voidcollections Viewers ***")]
  [TestCase("@warehousejesus Become popular with hightask.online")]
  [TestCase("@watsonater3000 We specialize in promoting Twitch channels — check out our website: nezhna .com")]
  [TestCase("@whatthedoink Best viewers  ***")]
  [TestCase("@whatthedoink Top viewers ***")]
  [TestCase("@yuki_yukiella Best viewers  ***")]
  [TestCase("Best viewers  ***  @1AzhE38Z")]
  [TestCase("B̬est viewers  on streamboo .com (remove the space)  @AttUaJmh")]
  [TestCase("Best viewers  smmtop30.ru  @dhXHYvcq")]
  [TestCase("Best viewers  streamboo .com (remove the space)  @463WnNVO")]
  [TestCase("Best Viewers streamboo .com")]
  [TestCase("B̬est viewers streamboo .com (remove the space)  @14ZPlFqw")]
  [TestCase("Cheap viewers  streamboo .com (remove the space)  @JH3UTAu7")]
  [TestCase("Cheap viewers boostcrest.ru  (free test)  @yFOh6kpc")]
  [TestCase("Cheap view͙e̤rs on streamboo .com (remove the space)  @bZQda7yE")]
  [TestCase("Cheap view͙e̤rs streamboo .com (remove the space)  @62Q4u8jo")]
  [TestCase("Cheap Viewers streamboo. live (remove the space)  @iDanXVO3")]
  [TestCase("Cheapest Viewers ***  @eBb2rjdv")]
  [TestCase("Cheapest viewers *** (free test)  @hKdD1LE7")]
  [TestCase("Cheapest Viewers cheapviewers4.online  @5UF6LJ20")]
  [TestCase("Cheapest Viewers streamboo. com (remove the space)  @IZgDg49C")]
  [TestCase("B\u0366est vie\u031fwers on streamboo .com ( remove the space )  @IBjZQcD1")]
  [TestCase("Cheap \u0314Viewers on  streamboo .com ( remove the space )  @kX9lOgg1")]
  [TestCase("B͐est vi̯ewers o͎n on streamboo .com ( remove the space )  @9F3Wnft0")]
  [TestCase("Ch̚eͅap viewers on ***  @STGPMoLg")]
  [TestCase("C̭heap viewe͌rs on̆ ***  @R1QXrXPM")]
  [TestCase("C̭heap viewe͌rs on̆ vwrpro.ru  @8v2JcQFL")]
  [TestCase("C\u032dheap viewe\u034crs on\u0306 vwrpro.ru @8v2JcQFL")]
  [TestCase("Ch\u031ae\u0345ap viewers on ***  @STGPMoLg")]
  [TestCase("Best\u036e vie\u0350wers \u0337on ***")]
  [TestCase("Best viewers on ***")]
  [TestCase("Best  viewers on ***")]
  [TestCase("Best vie̮wers on ***")]
  [TestCase("Best́ viewers on ***")]
  [TestCase("Be̩st Viewers on ***")]
  [TestCase("Be̾st Viewers on ***")]
  [TestCase("B͟est Viewers on ***")]
  [TestCase("B̟est viewers on ***")]
  [TestCase("Cheap viewers on ***")]
  [TestCase("Che̢ap vie̮wers on ***")]
  [TestCase("Ch̍eap Viewers on ***")]
  [TestCase("Ch͟eap viewers on ***")]
  [TestCase("C̀heap Viewers on ***")]
  [TestCase("Cheaͧp v̫iewers on ***")]
  [TestCase("Cheaͧp v̫iewers on *** ")]
  [TestCase("Cheap viewers ͚on followersboosters.ru  @U8y0GrKS")]
  [TestCase("Chea̓p viewers on streamboo. com (remove the space)  @ND80DOGe")]
  [TestCase("Bestͮ vie͐wers ̷on cutt.ly/EeK6Anda")]
  [TestCase("Bestͮ vie͐wers ̷on viewerszone.online")]
  [TestCase("Best viěw\u0310e\u0329rs \u0333o\u032bno\u034en streamboo .com ( remove the space )  @WSZ7tPNI")]
  public async Task TestKnownStrings(string badString) {
    var rule = new BestCheapViewers();
    var botProxy = new Mock<ITwitchApiProxy>();
    var chat = new TwitchChatMessage(true, badString, "123", "456");

    // Process the message and assert that we fail the message.
    bool result = await rule.Handle("123", botProxy.Object, chat, _db).ConfigureAwait(false);
    Assert.That(result, Is.False);
  }
}